"
Catalog of built-in Ollama model definitions.
"
Class {
	#name : 'OModelCatalog',
	#superclass : 'Object',
	#category : 'AI-Pharo-Copilot-Ollama',
	#package : 'AI-Pharo-Copilot-Ollama'
}

{ #category : 'private - definitions' }
OModelCatalog class >> codellama_13b [
  <ollamaModel: 'codellama' tag: '13b' label: 'Code Llama 13B'>
]

{ #category : 'private - definitions' }
OModelCatalog class >> codellama_13b_code [
  <ollamaModel: 'codellama' tag: '13b-code' label: 'Code Llama 13B Code'>
]

{ #category : 'private - definitions' }
OModelCatalog class >> codellama_7b [
  <ollamaModel: 'codellama' tag: '7b' label: 'Code Llama 7B'>
]

{ #category : 'private - definitions' }
OModelCatalog class >> codellama_7b_code [
  <ollamaModel: 'codellama' tag: '7b-code' label: 'Code Llama 7B Code'>
]
