Class {
	#name : 'CoPCEnvironmentMorphMock',
	#superclass : 'Object',
	#instVars : [
		'owner',
		'window'
	],
	#category : 'AI-Pharo-Copilot-Tests-Mock',
	#package : 'AI-Pharo-Copilot-Tests',
	#tag : 'Mock'
}

{ #category : 'accessing' }
CoPCEnvironmentMorphMock >> owner [

	^ owner
]

{ #category : 'accessing' }
CoPCEnvironmentMorphMock >> owner: anObject [

	owner := anObject
]

{ #category : 'accessing' }
CoPCEnvironmentMorphMock >> window [

	^ window
]

{ #category : 'accessing' }
CoPCEnvironmentMorphMock >> window: anObject [

	window := anObject
]
